### ISSUE TITLE
Managers

### ISSUE THREAD

**Issue by leeroar** [jotunnlib/jotunnlib#13]
- The managers in Jotunlib & TestMod seem to interfere with the already existing managers in the jotunnlib.dll in the VH dir.
- The ig console keeps replying with 'Invalid Command' on generally any- old and new command

**Comment by raduschirliu** [comment]
Hmm, what do you mean they seem to interfere? What sorts of errors are you getting?

**Comment by raduschirliu** [comment]
Not entirely sure what this is, so will be closing this issue for now, as we've found no errors or bugs related to this. Feel free to open another issue if the error persists.
