### ISSUE TITLE
Non-existing Thunderstore dependency

### ISSUE THREAD

**Issue by NeonCarbide** [jotunnlib/jotunnlib#16]
The current dependency on `bbepis-BepInExPack` in the Thunderstore version of the mod causes an error when trying to download the mod through r2modmanager as `bbepis-BepInExPack` does not exist as a package on Thunderstore

To resolve this issue, the dependency string for BepInEx should be changed to `denikson-BepInExPack_Valheim-5.4.800` in the manifest.json

**Comment by RatikKapoor** [comment]
Thanks for pointing this out @NeonCarbide, I've updated the dependency and pushed `v0.1.2` to Thunderstore. I won't be able to test until tonight but feel free to reopen the issue in case it still isn't working!

**Comment by NeonCarbide** [comment]
Everything works a-ok in `0.1.2`, thanks for the quick update ^-^

**Comment by RatikKapoor** [comment]
Awesome! You're more than welcome, enjoy modding or using the library 😄
