### ISSUE TITLE
Custom Prefab

### ISSUE THREAD

**Issue by CrudeWar** [jotunnlib/jotunnlib#17]
I only see how to create a prefab using models that already exist. Is there a way to create a prefab and load the mesh etc from an obj file? or a way to load in a custom asset bundle so that the prefab already exists?

**Comment by raduschirliu** [comment]
Yep, you should be able to! You can load a mesh from a .obj file using [this helper function](https://jotunnlib.github.io/jotunnlib/api/JotunnLib.Utils.AssetUtils.html#JotunnLib_Utils_AssetUtils_LoadMesh_System_String_), then set it on your prefab by changing it mesh on the mesh renderer component.

There's also [functionality in the library for creating a prefab from an object](https://github.com/jotunnlib/jotunnlib/blob/730fa30451541c1229436e53aa10cc3194493eb1/JotunnLib/Managers/PrefabManager.cs#L80), but it's currently set as internal so you'd have to do a bit of reflection magic to access it. We have some logic in place for the next version, v0.2.0, to make this process easier - this version should be released in around a week at most. But if you want to play around with it ahead of time, you could do something along these lines
```cs
// Here Paths.PluginPath is a variable from BepInEx
AssetBundle bundle = AssetBundle.LoadFromFile(Path.Combine(Paths.PluginPath, "TestMod/Assets/jotunnlibtest"));
GameObject testPrefab = (GameObject)bundle.LoadAsset("BundlePrefab");
ReflectionUtils.InvokePrivate(PrefabManager.Instance, "RegisterPrefab", new object[] { testPrefab, "BundlePrefab" });
```

**Comment by CrudeWar** [comment]
I am trying to load a custom asset and I am getting this error 
[Error  : Unity Log] NotImplementedException: The method or operation is not implemented.
Stack trace:
TestMod.TestMod.registerPrefabs (System.Object sender, System.EventArgs e) (at <293c3898612f4931acb497e71b96fa66>:0)
JotunnLib.Managers.PrefabManager.Load () (at <087b244f75474d8395ede17c672ab29f>:0)
JotunnLib.Patches.ZNetScenePatches+AwakePatch.Postfix () (at <087b244f75474d8395ede17c672ab29f>:0)
(wrapper dynamic-method) ZNetScene.DMD<ZNetScene::Awake>(ZNetScene)

this is the code i am using to do it. which i added in the register prefab section
AssetBundle bundle = AssetBundle.LoadFromFile(Path.Combine(Paths.PluginPath, "test.asset"));
            GameObject testPrefab = (GameObject)bundle.LoadAsset("GIRL");
            ReflectionUtils.InvokePrivate(PrefabManager.Instance, "RegisterPrefab", new object[] { testPrefab, "GIRL" });

I Added this later on to load it as a createable item 

ObjectManager.Instance.RegisterRecipe(new RecipeConfig()
            {
                // Name of the recipe (defaults to "Recipe_YourItem")
                Name = "Recipe_GIRL",

                // Name of the prefab for the crafted item
                Item = "GIRL",

                // Name of the prefab for the crafting station we wish to use
                // Can set this to null or leave out if you want your recipe to be craftable in your inventory
                CraftingStation = null,

                // List of requirements to craft your item
                Requirements = new PieceRequirementConfig[]
    {
                    new PieceRequirementConfig()
                    {
                        // Prefab name of requirement
                        Item = "Wood",

                        // Amount required
                        Amount = 2

**Comment by CrudeWar** [comment]
When I load a prefab from an asset file i am not getting any errors now but when it goes to create the item I am getting this.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
JotunnLib.Entities.RecipeConfig.GetRecipe () (at <f61a0622bfdb4b5bbd934ec1e630efed>:0)
JotunnLib.Managers.ObjectManager.RegisterRecipe (JotunnLib.Entities.RecipeConfig recipeConfig) (at <f61a0622bfdb4b5bbd934ec1e630efed>:0)
TestMod.TestMod.registerObjects (System.Object sender, System.EventArgs e) (at <40b408b6634640438d3b04c0f11f1da6>:0)
JotunnLib.Managers.ObjectManager.Register () (at <f61a0622bfdb4b5bbd934ec1e630efed>:0)
JotunnLib.Patches.ObjectDBPatches+AwakePatch.Postfix () (at <f61a0622bfdb4b5bbd934ec1e630efed>:0)
(wrapper dynamic-method) ObjectDB.DMD<ObjectDB::Awake>(ObjectDB)

I am using then newest jotun lib and test mod.

[TestMod.zip](https://github.com/jotunnlib/jotunnlib/files/6209186/TestMod.zip)
