### ISSUE TITLE
Can't Prefab without base 

### ISSUE THREAD

**Issue by Asgardrp** [jotunnlib/jotunnlib#26]
public MieczOdynaPrefab() : base("MieczOdyna") 
I want new item like this. But not working

**Comment by RatikKapoor** [comment]
Hi @Asgardrp, it's hard for us to pinpoint your issue with such little information. Please at least provide an error, stack trace, or screenshots I would recommend reading through our [guide on prefabs](https://jotunnlib.github.io/jotunnlib/tutorials/data/prefabs.html) as well!

**Comment by raduschirliu** [comment]
Just gonna throw in the error that you mentioned in the modding Discord:
```
[Info   : Unity Log] Loaded item: MieczOdyna
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
JotunnLib.Managers.ObjectManager.Load () (at <5bcb80cb71324c4a8acf1b13c1de00b9>:0)
JotunnLib.Patches.ObjectDBPatches+AwakePatch.Postfix () (at <5bcb80cb71324c4a8acf1b13c1de00b9>:0)
(wrapper dynamic-method) ObjectDB.DMD<ObjectDB::Awake>(ObjectDB)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<ObjectDB::Awake>?-826648576(ObjectDB)
ValheimLib.ODB.ObjectDBHelper.AddCustomData (On.ObjectDB+orig_Awake orig, ObjectDB self) (at <5f36a1563d4442b8a841887b90fe36e9>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<ObjectDB::Awake>?463454720(ObjectDB)
```

**Comment by RatikKapoor** [comment]
@Asgardrp if possible please link us to your source code if it's pushed on git. It'll be easier to repro that way.

**Comment by Asgardrp** [comment]
https://github.com/Asgardrp/Quest

**Comment by Asgardrp** [comment]
@raduschirliu @RatikKapoor

**Comment by Asgardrp** [comment]
Im try to create like mod "StaticCleaver". Create item in unity3d and still not work.
https://github.com/Asgardrp/MieczOdyna

 
[Error  : Unity Log] Error, recipe contained null item prefab for item: MieczOdyna1
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object Stack trace:
JotunnLib.Entities.PieceRequirementConfig.GetPieceRequirement () (at <5bcb80cb71324c4a8acf1b13c1de00b9>:0)
JotunnLib.Entities.RecipeConfig.GetRecipe () (at <5bcb80cb71324c4a8acf1b13c1de00b9>:0)
JotunnLib.Managers.ObjectManager.RegisterRecipe (JotunnLib.Entities.RecipeConfig recipeConfig) (at <5bcb80cb71324c4a8acf1b13c1de00b9>:0)
MasterChef.MasterChef.registerObjects (System.Object sender, System.EventArgs e) (at <e9454e615c8e4037bb1bc8e370c2ecdf>:0)
JotunnLib.Managers.ObjectManager.Register () (at <5bcb80cb71324c4a8acf1b13c1de00b9>:0)
JotunnLib.Patches.ObjectDBPatches+AwakePatch.Postfix () (at <5bcb80cb71324c4a8acf1b13c1de00b9>:0)
(wrapper dynamic-method) ObjectDB.DMD<ObjectDB::Awake>(ObjectDB)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<ObjectDB::Awake>?-2032570368(ObjectDB)
ValheimLib.ODB.ObjectDBHelper.AddCustomData (On.ObjectDB+orig_Awake orig, ObjectDB self) (at <66dec4d05d8743eb8424a906129f16d8>:0)
 (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<ObjectDB::Awake>?1292988416(ObjectDB)

**Comment by Asgardrp** [comment]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
JotunnLib.Managers.ObjectManager.Load () (at <5bcb80cb71324c4a8acf1b13c1de00b9>:0)
JotunnLib.Patches.ObjectDBPatches+AwakePatch.Postfix () (at <5bcb80cb71324c4a8acf1b13c1de00b9>:0)
(wrapper dynamic-method) ObjectDB.DMD<ObjectDB::Awake>(ObjectDB)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<ObjectDB::Awake>?-88674304(ObjectDB)
ValheimLib.ODB.ObjectDBHelper.AddCustomData (On.ObjectDB+orig_Awake orig, ObjectDB self) (at <66dec4d05d8743eb8424a906129f16d8>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<ObjectDB::Awake>?-552188160(ObjectDB)
