### ISSUE TITLE
Non-existing Thunderstore dependency

### ISSUE THREAD

**Issue by NeonCarbide** [jotunnlib/jotunnlib#29]
The exact same bug in issue #16 has returned

All references to BepInEx for dependencies should reference [denikson's package on Thunderstore](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/)

**Comment by RatikKapoor** [comment]
Ahh shoot thanks for pointing this out again, our bad. @raduschirliu Maybe push the manifest to git so that whoever uploads the mod to Thunderstore between us has the latest version

**Comment by raduschirliu** [comment]
Damn, entirely my bad there, used the wrong manifest when uploading... Thank you for pointing that out again, promise this is the last time we'll make that mistake :)

**Comment by RatikKapoor** [comment]
Pushed v0.1.4 to Thunderstore and PR'd fix for manifest
