### ISSUE TITLE
Issue during game load

### ISSUE THREAD

**Issue by AMurtagh** [jotunnlib/jotunnlib#41]
Appreciate this may not be a concern given the merger and feel free to close if so. When the game loads, consistently every time it presents the following error in the BepinEx console:

`[Error  : Unity Log] ArgumentException: Undefined target method for patch method static void JotunnLib.Patches.ConsoleCommandsPatches+ConsoleInputTextPatch::Postfix(Console& __instance)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
HarmonyLib.Harmony.PatchAll () (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
JotunnLib.JotunnLib.Awake () (at <9d5e45e8ae9f49e4a401a87ca18f201b>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
`

I have also attached a photo showing the error in-place with the pre and post content from the console window.

![image](https://user-images.githubusercontent.com/29312080/138510145-e5e99f06-9e5a-4c96-9c4d-d6001f282cad.png)

**Comment by Tattiana85** [comment]
I am also having this same issue.   I can not find any helpful information ANYWHERE on how to deal with this.  Has a resolution been found?

**Comment by raduschirliu** [comment]
Sorry for the late reply here - it seems this is due to the recent Valheim update that overhauled how their console commands work. I'll look into it over the next couple of days and try to release a fix soon

**Comment by Tattiana85** [comment]
Hey it's ok, thanks for the reply! 🙂
